version: '3'
services:

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/restaurant/:/var/www/restaurant
      - ./apps/ms-warehouse/:/var/www/ms-warehouse
      - ./apps/ms-kitchen/:/var/www/ms-kitchen
      - ./apps/ms-market/:/var/www/ms-market
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    networks:
      - app-network

  restaurant:
    build:
      context: apps/restaurant
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: restaurant
      SERVICE_TAGS: dev
    working_dir: /var/www/restaurant
    volumes:
      - ./apps/restaurant/:/var/www/restaurant
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  warehouse:
    build:
      context: apps/ms-warehouse
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: warehouse
      SERVICE_TAGS: dev
    working_dir: /var/www/ms-warehouse
    volumes:
      - ./apps/ms-warehouse/:/var/www/ms-warehouse
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  
  kitchen:
    build:
      context: apps/ms-kitchen
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: kitchen
      SERVICE_TAGS: dev
    working_dir: /var/www/ms-kitchen
    volumes:
      - ./apps/ms-kitchen/:/var/www/ms-kitchen
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  market:
    build:
      context: apps/ms-market
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: market
      SERVICE_TAGS: dev
    working_dir: /var/www/ms-market
    volumes:
      - ./apps/ms-market/:/var/www/ms-market
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_PASSWORD: alegra
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass aLeGrA_pAsS
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis-data:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
